name: First Workflow
on: workflow_dispatch # Ability to start workflow manually
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello world"
          echo "Second hello"
      - name: Print goodbye
        run: echo "Bye"
